import Head from 'next/head'
import NavBar from '../src/components/NavBar/NavBar'
import Body from '../src/components/Body/Body'
import About from '../src/components/About/About'
import Projects from '../src/components/Projects/Projects'
import Contact from '../src/components/Contact/Contact'
export default function Home() {
  return (
    <>
      <Head>
        <title>Gabriel Wojcik | Portfólio</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

           <NavBar />
           <Body />
           <About />
           <Projects />
           <Contact />
      </>
  )
}
